### ISSUE TITLE
HasGarten Verification File

### ISSUE THREAD

**Issue by mweberr** [jonelo/HashGarten#6]
How does a valid verification file look like ?
I receive an error : "Jack sum error not even one valid entry has been found in file.md5"

Usually, two columns are sufficient one for the hash value and one for the file.

Best, Michael

**Comment by jonelo** [comment]
Michael, actually Jacksum/HashGarten supports 10 different integrity verification file formats by default (you can even create your own if you want). You can select the Integrity Verifcation File Format in the Verification Tab. If you click on the question mark button you can get more details for each format.

![0lukHYhpw4](https://github.com/jonelo/HashGarten/assets/10409423/15b2146a-9595-42eb-83d2-38e1bd6ccf47)

Usually the default should be suitable to meet your needs (two columns). Which style did you set? If you attach your file.md5 to this report I can have a look at it.

Cheers, Johann

**Comment by mweberr** [comment]
Hi, Thanks for your answer. I figured out that relative paths in MD5 file are the solution.
1) I generated the MD5 file with relative paths in original directory.
2) Copied it to target directory
3) Started verification.

What is the meaning of an asterisk ? 6a7f168c701c59c63322eab021222e6e *sample.fq.gz

Is this the usualy procedure ?

**Comment by jonelo** [comment]
The asterisk has a special meaning on some systems how the input was being processed. Here is an excerpt from the md5 manpage on GNU/Linux:

> The default mode is to print a line with: checksum, a space, a character indicating input mode ('*' for binary, ' ' for text or where binary is insignificant), and name for each file.
> Note: There is no difference between binary mode and text mode on GNU systems.

Jacksum always read files in binary mode on all platforms, so also for Jacksum 3.x there is no difference between binary mode and text mode if an asterisk is found in hash files.

> Is this the usualy procedure ?

It depends on the actual use case. If paths are stored relatively in the hash file, you could read from the hash file directly during verification process rather than copying it.

Does that answer your questions?

**Comment by jonelo** [comment]
closed due to inactivity for 3+ months.
