### ISSUE TITLE
HashGarten 0.17 Wrong Output File

### ISSUE THREAD

**Issue by mweberr** [jonelo/HashGarten#7]
Hi, I changed the Standard Output file in the fourth tab of HashGarten. But the output is not written anymore to it.
Instead, the Error log generates Errors for files which are not anymore part of the Input Files and Directories.

Are there any temporary files used by HashGarten, which I need to delete to continue ?

Best, Michael

**Comment by jonelo** [comment]
Michael, thank you for the report! I have transferred the issue to the HashGarten project because it is not related to Jacksum directly.

Referring to your description of the faut, this could be a remnant from an older version. Could you please try the following:

1. Close HashGarten
2. Remove the `.HashGarten.properties` file. You find the file in your homedirectory.
3. Open HashGarten again

Here are the instructions dependent on the operating system how to remove the file on the command line/Terminal:

OS      | How to remove HashGarten's properties?        | 
--------|-----------------------------------------------|
Windows | `del "%USERPROFILE%"\.HashGarten.properties`  |
macOS and Linux   | `rm "$HOME/.HashGarten.properties"`           |

**Comment by mweberr** [comment]
This helped!
